
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - topology.vkubeviewer.com
  resources:
  - datastoreinfoes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - topology.vkubeviewer.com
  resources:
  - datastoreinfoes/finalizers
  verbs:
  - update
- apiGroups:
  - topology.vkubeviewer.com
  resources:
  - datastoreinfoes/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - topology.vkubeviewer.com
  resources:
  - fcdinfoes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - topology.vkubeviewer.com
  resources:
  - fcdinfoes/finalizers
  verbs:
  - update
- apiGroups:
  - topology.vkubeviewer.com
  resources:
  - fcdinfoes/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - topology.vkubeviewer.com
  resources:
  - hostinfoes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - topology.vkubeviewer.com
  resources:
  - hostinfoes/finalizers
  verbs:
  - update
- apiGroups:
  - topology.vkubeviewer.com
  resources:
  - hostinfoes/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - topology.vkubeviewer.com
  resources:
  - vminfoes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - topology.vkubeviewer.com
  resources:
  - vminfoes/finalizers
  verbs:
  - update
- apiGroups:
  - topology.vkubeviewer.com
  resources:
  - vminfoes/status
  verbs:
  - get
  - patch
  - update
